name: login_page_pmsf
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^2.4.0
  firebase_database: ^10.0.9
  firebase_auth: ^4.2.0
  flutter_native_splash: ^2.2.16
  validatorless: ^1.2.3
  page_transition: ^2.0.9
  flutter_launcher_icons: ^0.11.0
  
  modal_bottom_sheet: ^2.1.2
  top_snackbar_flutter: ^3.0.0+1
  cloud_firestore: ^4.3.2
  flutter_animate: ^4.0.0
  hidden_drawer_menu: ^3.0.1

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

  

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  match_generator: ^0.4.1

flutter_native_splash:
  image: assets/splash_screen_loginlight.png
  color: "#e0e0e0"
  android_12:
    image: assets/splash_screen_loginlight.png
  image_dark: assets/splash_screen_logindark.png
  color_dark: "#131515"
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
