// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKBPc-Al9SKxUOO7VC_UUExTw-RIPggzE',
    appId: '1:409414155696:web:c478308f547712553baa75',
    messagingSenderId: '409414155696',
    projectId: 'login-page-db-pmsf',
    authDomain: 'login-page-db-pmsf.firebaseapp.com',
    databaseURL: 'https://login-page-db-pmsf-default-rtdb.firebaseio.com',
    storageBucket: 'login-page-db-pmsf.appspot.com',
    measurementId: 'G-GWNJXG33DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyDrt75udggJGUEMbG5r9Yp6PxMdcAQ1s',
    appId: '1:409414155696:android:cb5d7a3fb715eec93baa75',
    messagingSenderId: '409414155696',
    projectId: 'login-page-db-pmsf',
    databaseURL: 'https://login-page-db-pmsf-default-rtdb.firebaseio.com',
    storageBucket: 'login-page-db-pmsf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-dDp1_uetC8swmnTYFue2fVOEQYjJ-s',
    appId: '1:409414155696:ios:e52806f62c324ea33baa75',
    messagingSenderId: '409414155696',
    projectId: 'login-page-db-pmsf',
    databaseURL: 'https://login-page-db-pmsf-default-rtdb.firebaseio.com',
    storageBucket: 'login-page-db-pmsf.appspot.com',
    iosClientId: '409414155696-4r82sb97otkjig8h5h5afhflrn1dolv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPagePmsf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-dDp1_uetC8swmnTYFue2fVOEQYjJ-s',
    appId: '1:409414155696:ios:e52806f62c324ea33baa75',
    messagingSenderId: '409414155696',
    projectId: 'login-page-db-pmsf',
    databaseURL: 'https://login-page-db-pmsf-default-rtdb.firebaseio.com',
    storageBucket: 'login-page-db-pmsf.appspot.com',
    iosClientId: '409414155696-4r82sb97otkjig8h5h5afhflrn1dolv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPagePmsf',
  );
}
